### ISSUE TITLE
deployments() fails to get deployed applications

### ISSUE THREAD

**Issue by zsuzhengdu** [cenx-cf/wildfly-py#1]
Run 

``` python
import wildfly

WILDFLYHOST = anyone_other_than_default  # tools01.cenx.localnet

client = wildfly.Client(WILDFLYHOST)

client.deployments()
```

Found errors blow

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/wildfly/api/deployment.py", line 41, in deployments
    servers = self.servers()
  File "/usr/lib/python2.7/site-packages/wildfly/api/server.py", line 19, in servers
    for key, value in servers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by zsuzhengdu** [comment]
Can not reproduce.
